ALTER TABLE `products` ADD COLUMN `minimum_quantity` integer DEFAULT 1 NOT NULL;--> statement-breakpoint
UPDATE `products`
SET `is_active` = 0,
    `sku` = `sku` || '-ARCHIVED-' || `id`,
    `slug` = `slug` || '-archived-' || `id`,
    `updated_at` = CURRENT_TIMESTAMP;--> statement-breakpoint
INSERT INTO `products` (`id`,`slug`,`sku`,`name`,`short_description`,`description`,`category`,`product_type`,`base_price_cents`,`currency`,`material`,`image_url`,`personalization_schema_json`,`attributes_json`,`lead_time_min_days`,`lead_time_max_days`,`minimum_quantity`,`is_active`,`is_featured`,`sort_order`) VALUES
('PG-01','custom-photo-lithophane-night-light','BL-LITHO-001','Photo Lithophane Night Light','Turn a favorite photo into a softly glowing keepsake.','Upload a photo, choose its orientation and add an optional caption. We review the image before production.','Gifts & Personalization','personalized',3999,'USD','PLA','/products/custom-photo-lithophane-night-light.png','[{"key":"photo","label":"Photo","type":"file","required":true},{"key":"orientation","label":"Orientation","type":"select","required":true,"options":["Portrait","Landscape"]},{"key":"caption","label":"Caption","type":"text","required":false,"maxLength":60}]','{"colors":["Cream","Forest","Rose","Ocean","Charcoal"],"safety":"Use only with the included low-heat LED light."}',3,5,1,1,1,10),
('PG-05','pet-memorial-silhouette-stand','BL-PET-001','Pet Memorial Silhouette Stand','A quiet custom silhouette keepsake made from your pet photo.','Upload a clear pet photo and add a name or short memorial line for review before printing.','Gifts & Personalization','personalized',3999,'USD','PLA','/products/pet-memorial-silhouette-stand.png','[{"key":"photo","label":"Pet photo","type":"file","required":true},{"key":"petName","label":"Pet name","type":"text","required":true,"maxLength":40},{"key":"memorialLine","label":"Memorial line","type":"text","required":false,"maxLength":80}]','{"colors":["Cream","Forest","Rose","Ocean","Charcoal"]}',3,5,1,1,1,20),
('SE-04','teacher-name-desk-sign','BL-NAME-001','Teacher & Office Nameplate','A personalized nameplate for a classroom, studio, or office.','Choose colors and enter the exact name and role for a proof before production.','Seasonal','personalized',2999,'USD','PLA','/products/custom-name-desk-sign.png','[{"key":"name","label":"Name","type":"text","required":true,"maxLength":40},{"key":"role","label":"Role or room","type":"text","required":false,"maxLength":60}]','{"colors":["Cream","Forest","Rose","Ocean","Charcoal"]}',2,4,1,1,1,30),
('BE-01','wedding-place-name','BL-WEDDING-001','Wedding Place Names','Freestanding guest names that double as personal favors.','Provide one guest name per line. Names are proofed and packed in seating-list order.','Business & Events','personalized',349,'USD','PLA','/products/personalized-name-desk-sign.png','[{"key":"names","label":"Guest names","type":"textarea","required":true,"maxLength":2000},{"key":"eventDate","label":"Event date","type":"date","required":true}]','{"colors":["Cream","Forest","Rose","Ocean","Charcoal"]}',4,7,20,1,1,40),
('BE-03','qr-review-payment-sign','BL-QR-001','QR / NFC Business Sign','A branded counter sign configured and test-scanned before delivery.','Add the exact destination URL, business name and optional approved logo. NFC is available as an option.','Business & Events','personalized',3499,'USD','PLA + optional NFC','/products/custom-qr-display-sign.png','[{"key":"destinationUrl","label":"Destination URL","type":"url","required":true},{"key":"businessName","label":"Business name","type":"text","required":true,"maxLength":60},{"key":"logo","label":"Approved logo","type":"file","required":false},{"key":"nfc","label":"NFC option","type":"select","required":true,"options":["QR only","QR + NFC"]}]','{"colors":["Forest","Cream","Terracotta","Ocean","Charcoal"]}',3,5,1,1,1,50),
('CP-02','replacement-part-reproduction','BL-PART-001','Replacement-Part Design Service','Design help for a practical, non-safety-critical replacement.','Send measurements, photos and use details. The checkout covers the design setup; print cost is quoted after review.','Custom 3D Print','service',3900,'USD','PETG','/products/replacement-part-reproduction.png','[{"key":"partDescription","label":"Part and use","type":"textarea","required":true,"maxLength":1000},{"key":"dimensions","label":"Measurements","type":"text","required":true,"maxLength":200},{"key":"reference","label":"Reference photo","type":"file","required":true}]','{"colors":["Forest","Cream","Terracotta","Ocean","Charcoal"],"safety":"No automotive safety, medical, electrical, pressure, weapon, or child-safety parts."}',5,8,1,1,1,60),
('GH-04','hobby-paint-bottle-rack','BL-PAINT-001','Modular Hobby Paint Rack','Tiered storage for up to 24 common hobby paints.','Choose the bottle diameter and color so the rack fits the supplies you actually use.','Gaming & Hobbies','made_to_order',3999,'USD','PLA','/products/hobby-paint-bottle-rack.png','[{"key":"bottleDiameter","label":"Bottle diameter","type":"select","required":true,"options":["25 mm","32 mm","36 mm"]},{"key":"layout","label":"Layout","type":"select","required":true,"options":["Straight","Corner"]}]','{"colors":["Forest","Cream","Terracotta","Ocean","Charcoal"]}',4,6,1,1,1,70),
('PD-01','self-watering-planter','BL-PLANT-001','Self-Watering Planter','A two-piece planter that makes moisture levels easy to check.','Choose a size and color. Each reservoir is leak-tested before packing.','Plants & Decor','made_to_order',3199,'USD','PETG','/products/self-watering-planter.png','[{"key":"size","label":"Size","type":"select","required":true,"options":["Small","Medium"]},{"key":"drainage","label":"Inner pot","type":"select","required":true,"options":["Standard wick","Extra drainage"]}]','{"colors":["Forest","Cream","Terracotta","Ocean","Charcoal"]}',3,5,1,1,1,80)
ON CONFLICT(`id`) DO UPDATE SET `slug`=excluded.`slug`,`sku`=excluded.`sku`,`name`=excluded.`name`,`short_description`=excluded.`short_description`,`description`=excluded.`description`,`category`=excluded.`category`,`product_type`=excluded.`product_type`,`base_price_cents`=excluded.`base_price_cents`,`currency`=excluded.`currency`,`material`=excluded.`material`,`image_url`=excluded.`image_url`,`personalization_schema_json`=excluded.`personalization_schema_json`,`attributes_json`=excluded.`attributes_json`,`lead_time_min_days`=excluded.`lead_time_min_days`,`lead_time_max_days`=excluded.`lead_time_max_days`,`minimum_quantity`=excluded.`minimum_quantity`,`is_active`=1,`is_featured`=excluded.`is_featured`,`sort_order`=excluded.`sort_order`,`updated_at`=CURRENT_TIMESTAMP;--> statement-breakpoint
PRAGMA optimize;
