INSERT INTO `products` (`id`,`slug`,`sku`,`name`,`short_description`,`description`,`category`,`product_type`,`base_price_cents`,`currency`,`material`,`image_url`,`personalization_schema_json`,`attributes_json`,`lead_time_min_days`,`lead_time_max_days`,`minimum_quantity`,`is_active`,`is_featured`,`sort_order`) VALUES
('PG-03','custom-name-desk-sign','BL-DESKSIGN-001','Custom Name Desk Sign','A layered nameplate sized, colored, and lettered for their space.','Choose a color and enter the name and optional subtitle for a proof before production.','Gifts & Personalization','personalized',2499,'USD','PLA','/products/custom-name-desk-sign.png','[{"key":"name","label":"Name","type":"text","required":true,"maxLength":40},{"key":"subtitle","label":"Subtitle","type":"text","required":false,"maxLength":60}]','{"colors":["Cream","Forest","Rose","Ocean","Charcoal"]}',3,4,1,1,1,90),
('PG-04','personalized-name-bag-tag','BL-BAGTAG-001','Personalized Name Bag Tag','A durable two-color tag for backpacks, luggage, and everyday carry.','Enter the name to engrave on this two-color tag.','Gifts & Personalization','personalized',799,'USD','PETG','/products/personalized-name-bag-tag.png','[{"key":"name","label":"Name","type":"text","required":true,"maxLength":20}]','{"colors":["Cream","Forest","Rose","Ocean","Charcoal"]}',2,3,1,1,0,100),
('PD-02','propagation-station','BL-PROP-001','Propagation Station with Glass Tubes','A stable three-tube stand for watching new roots take shape.','Choose a color; each stand ships with three glass propagation tubes.','Plants & Decor','made_to_order',2999,'USD','PETG + glass','/products/propagation-station.png','[]','{"colors":["Forest","Cream","Terracotta","Ocean","Charcoal"]}',4,5,1,1,0,110),
('PD-03','geometric-planter-trio','BL-GEOPLANT-001','Geometric Planter Trio','Three coordinated small planters for succulents and desk plants.','Choose a color for the coordinated three-planter set.','Plants & Decor','made_to_order',3299,'USD','PETG','/products/geometric-planter-trio.png','[]','{"colors":["Forest","Cream","Terracotta","Ocean","Charcoal"]}',5,6,1,1,0,120),
('PD-04','hanging-air-plant-holder','BL-AIRPLANT-001','Hanging Air-Plant Holder','A light sculptural cradle designed for small air plants.','Choose a color for this hanging air-plant cradle.','Plants & Decor','made_to_order',1699,'USD','PETG','/products/hanging-air-plant-holder.png','[]','{"colors":["Forest","Cream","Terracotta","Ocean","Charcoal"]}',2,3,1,1,0,130),
('GH-01','modular-tabletop-token-trays','BL-TOKENTRAY-001','Modular Tabletop Token Trays','Stackable trays keep shared tokens visible and the table moving.','Choose a color for this stackable token tray set.','Gaming & Hobbies','made_to_order',1899,'USD','PLA','/products/modular-tabletop-token-trays.png','[]','{"colors":["Forest","Cream","Terracotta","Ocean","Charcoal"]}',3,4,1,1,1,140),
('GH-05','trading-card-display-stands','BL-CARDSTAND-001','Trading-Card Display Stands','Low-profile stands that frame favorite cards without covering them.','Choose a color for this set of three card display stands.','Gaming & Hobbies','made_to_order',1499,'USD','PLA','/products/trading-card-display-stands.png','[]','{"colors":["Forest","Cream","Terracotta","Ocean","Charcoal"]}',2,3,1,1,0,150),
('GH-06','universal-board-game-organizer','BL-BOARDORG-001','Universal Board-Game Organizer','Configurable trays for cards, cubes, coins, and common components.','Choose a color for this configurable board-game organizer.','Gaming & Hobbies','made_to_order',2999,'USD','PLA','/products/universal-board-game-organizer.png','[]','{"colors":["Forest","Cream","Terracotta","Ocean","Charcoal"]}',5,6,1,1,0,160),
('SE-01','holiday-ornament','BL-ORNAMENT-001','Personalized Holiday Ornament','A name-and-year keepsake with a choice of modern motifs.','Enter a name and optional year for this holiday ornament.','Seasonal','personalized',1499,'USD','PLA','/products/personalized-ornament.png','[{"key":"name","label":"Name","type":"text","required":true,"maxLength":24},{"key":"year","label":"Year","type":"text","required":false,"maxLength":4}]','{"colors":["Cream","Forest","Rose","Ocean","Charcoal"]}',2,3,1,1,0,170),
('SE-06','valentine-coordinates-keepsake','BL-VALCOORD-001','Valentine Coordinates Keepsake','A minimal reminder of where your story began.','Enter coordinates and an optional date for this keepsake.','Seasonal','personalized',1999,'USD','PLA','/products/coordinates-date-keepsake.png','[{"key":"coordinates","label":"Coordinates","type":"text","required":true,"maxLength":60},{"key":"date","label":"Date","type":"text","required":false,"maxLength":30}]','{"colors":["Cream","Forest","Rose","Ocean","Charcoal"]}',3,4,1,1,0,180),
('SE-07','family-photo-lithophane','BL-FAMLITHO-001','Family Photo Lithophane','A framed glowing photo gift for any occasion.','Upload a photo, choose its orientation and add an optional caption. We review the image before production.','Seasonal','personalized',3499,'USD','PLA','/products/custom-photo-lithophane-night-light.png','[{"key":"photo","label":"Photo","type":"file","required":true},{"key":"orientation","label":"Orientation","type":"select","required":true,"options":["Portrait","Landscape"]},{"key":"caption","label":"Caption","type":"text","required":false,"maxLength":60}]','{"colors":["Cream","Forest","Rose","Ocean","Charcoal"]}',4,6,1,1,0,190),
('BE-02','table-number-set','BL-TABLENUM-001','Table Number Set','A coordinated set of modern, highly legible table numbers 1 through 10.','Add an optional numbering note before production.','Business & Events','personalized',4999,'USD','PLA','/products/table-number-set.png','[{"key":"note","label":"Numbering note","type":"text","required":false,"maxLength":120}]','{"colors":["Cream","Forest","Rose","Ocean","Charcoal"]}',5,7,1,1,0,200),
('BE-05','branded-bag-tags','BL-BIZBAGTAG-001','Branded Bag Tags','Durable branded tags for teams, events, or customer gifts.','Enter the tag text and an optional approved logo for review before production.','Business & Events','personalized',9900,'USD','PETG','/products/personalized-name-bag-tag.png','[{"key":"text","label":"Tag text","type":"text","required":true,"maxLength":24},{"key":"logo","label":"Approved logo","type":"file","required":false}]','{"colors":["Forest","Cream","Terracotta","Ocean","Charcoal"]}',8,10,1,1,0,210);
